# Generated by Django 2.2.5 on 2019-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
