# Generated by Django 2.2.6 on 2019-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alerts_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='offer',
            field=models.BooleanField(),
        ),
    ]
