# Generated by Django 2.2.6 on 2019-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191004_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pending',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tasks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
